src/Entity/Video.php
<?php

namespace App\Entity;

use App\Entity\Property\LazyProperty;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

class Video
{
    protected $id;

    protected $extId;

    protected $website;

    protected $user;

    protected $channels;

    protected $comments;

    protected $name;

    protected $description;

    protected $thumbnail;

    protected $thumbnails;

    protected $token;

    protected $rates;

    protected $rating = 0;

    protected $keywords;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->rates = new ArrayCollection();
        $this->thumbnails = new ArrayCollection();
        $this->keywords = new ArrayCollection();
        $this->channels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getExtId(): ?string
    {
        return $this->extId;
    }

    public function setExtId(string $extId): self
    {
        $this->extId = $extId;

        return $this;
    }

    public function getWebsite(): ?Website
    {
        return $this->website;
    }

    public function setWebsite(Website $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getChannels(): Collection
    {
        return $this->channels;
    }

    public function setChannels(Collection $channels): self
    {
        $this->channels = $channels;

        return $this;
    }

    public function addChannel(Channel $channel): self
    {
        $this->channels[] = $channel;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * main thubmnail
     */
    public function getThumbnail(): ?Thumbnail
    {
        return $this->thumbnail;
    }

    public function setThumbnail(Thumbnail $thumbnail): self
    {
        $thumbnail->setVideo($this);

        $this->thumbnail = $thumbnail;

        return $this;
    }

    /**
     *  list of thumbnails
     */
    public function getThumbnails(): Collection
    {
        return $this->thumbnails;
    }

    public function setThumbnails(Collection $thumbnails): self
    {
        $this->thumbnails = $thumbnails;

        return $this;
    }

    public function getPlayerId(): ?string
    {
        return $this->getWebsite()->getDataSource()->getVmproPlayerId();
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(LazyProperty $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getRating(): int
    {
        return $this->rating;
    }

    public function addRate(Rate $rate): self
    {
        if (!$this->getWebsite()->getFeature()->isRating()) {
            throw new \Exception('Feature rating is disabled');
        }

        $rate->setVideo($this);

        $this->rates[] = $rate;

        //@TODO or recalculate it in video repo
        $this->rating = $this->rating + $rate->getValue();

        return $this;
    }

    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->getWebsite()->getFeature()->isComment()) {
            throw new \Exception('Feature comment is disabled');
        }

        $comment->setVideo($this);

        $this->comments[] = $comment;

        return $this;
    }

    public function getKeywords(): Collection
    {
        return $this->keywords;
    }

    public function setKeywords(Collection $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function isStartWebsite(): bool
    {
        $sourceStartVideo = $this->getWebsite()->getSourceStartVideo();
        return $sourceStartVideo && $this->getId() === $sourceStartVideo->getId();
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Website;
use App\Repository\UserRepository;
use App\Repository\VideoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class VideoController extends AbstractController
{
    private $videoRepository;

    private $userRepository;

    public function __construct(VideoRepository $videoRepository, UserRepository $userRepository)
    {
        $this->videoRepository = $videoRepository;
        $this->userRepository = $userRepository;
    }

    public function index(string $extId, Request $request)
    {
        /** @var Website $website */
        $website = $this->getDoctrine()->getRepository(Website::class)->findOneByHost($request->getHost());

        $video = $this->videoRepository->find($website, $extId);

        $user = $this->userRepository->findFake($website);

        $isVideoFavorite = $user->isVideoFavorite($video);

        $relatedVideos = [];
        if ($website->getFeature()->isRelatedVideos()) {
            $relatedVideos = $this->videoRepository->findRelatedVideos($video);
        }

        return $this->render('video/index.html.twig', [
            'video' => $video,
            'relatedVideos' => $relatedVideos,
            'website' => $website,
            'menu' => $website->getMenu(),
            'isFavorite' => $isVideoFavorite
            ]
        );
    }

    public function setStartWebsite(string $extId, Request $request)
    {
        /** @var Website $website */
        $website = $this->getDoctrine()->getRepository(Website::class)->findOneByHost($request->getHost());

        $video = $this->videoRepository->find($website, $extId);

        $website->setSourceStartVideo($video);

        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('video', ['extId' => $video->getExtId()]);
    }

    public function resetStartWebsite(string $extId, Request $request)
    {
        /** @var Website $website */
        $website = $this->getDoctrine()->getRepository(Website::class)->findOneByHost($request->getHost());

        $website->setSourceStartVideo(null);

        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('video', ['extId' => $extId]);
    }
}

templates/video/_list.html.twig
{% if videos is not empty %}
    <div class="b-videos" >
        {% for video in videos %}
            <div class="b-video">
                <a href="{{ url('video', { 'extId': video.extId, 'channelId': channel is defined ? channel.extId : null }) }}" class="e-thumbnail"><img src="{{ video.thumbnail ? video.thumbnail.url : '' }}" ></a>
                <div class="e-name">{{ video.name }}</div>
                {% if editable is defined %}
                    <a href="{{ url('videoUpdate', {'extId': video.extId }) }}" class="e-edit">Edit</a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/video/_videoBig.html.twig
{% if video %}
    <div class="b-videoBig">
        <h1>{{ video.name }}</h1>

        <div id="player_container" class="e-player"
             mi24-video-player
             video-id="{{ video.extId }}"
             player-id="{{ video.playerId }}"
             config-type="vmpro"
             flash-path="//e.video-cdn.net/v2/"
             token="{{ video.token }}"
             api-url="//d.video-cdn.net/play">
        </div>

        <div class="e-description">
            {{ video.description }}
        </div>

        {% if video.website.feature.isRating %}
            <div class="e-rating">
                <div class="e-value">rating: {{ video.rating }}</div>
                <a href="{{ url('rating', {'extId': video.extId, 'value': 'dislike' }) }}" class="e-dislike"></a>
                <a href="{{ url('rating', {'extId': video.extId, 'value': 'like' }) }}" class="e-like"></a>
            </div>
        {% endif %}

        <div class="e-favorite">
            {% if isFavorite is defined and isFavorite %}
                <a href="{{ url('removeVideoFromFavorite', {'extId': video.extId}) }}" class="e-remove"></a>
            {% else %}
                <a href="{{ url('addVideoToFavorite', {'extId': video.extId}) }}" class="e-add"></a>
            {% endif %}
        </div>

        <div class="e-setStartVideo">
            {% if video.isStartWebsite %}
                <a href="{{ url('resetStartWebsiteVideo', {extId:video.extId}) }}">Remove start video</a>
            {% else %}
                <a href="{{ url('setStartWebsiteVideo', {extId:video.extId}) }}">Set start video</a>
            {% endif %}
        </div>
    </div>
{% endif %}

templates/video/form.html.twig
{% extends 'base.html.twig' %}
{% block headTitle %}{{ website.name }}{% endblock %}
{% block body %}

    <div class="b-videoForm">
        {{ form_start(form) }}
        <div class="e-left e-form">
            {{ form_rest(form) }}
        </div>
        <div class="e-right">
            {% if video is defined and video and video.thumbnails is not empty %}
                <div class="b-thumbnails">
                {% for thumbnail in video.thumbnails %}
                 <div class="e-thumbnail">
                     <input type="radio" name="form[thumbnailId]" value="{{ thumbnail.id }}" id="thumbnail{{ thumbnail.id }}">
                     <label for="thumbnail{{ thumbnail.id }}">
                        <img alt="" src="{{ thumbnail.url }}">
                     </label>
                 </div>
                {% endfor %}
                </div>
            {% endif %}
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}
{% block headTitle %}{{ website.name }}{% endblock %}
{% block body %}

    <div class="b-videoPage">

        {{ include('video/_videoBig.html.twig') }}

        {% if video.website.feature.isRelatedVideos %}
            <div class="b-relatedVideos">
                {{ include('video/_list.html.twig', {'videos': relatedVideos }) }}
            </div>
        {% endif %}

        <div class="clear"></div>

        {% if video.website.feature.isComment %}

            {{ include('comment/_list.html.twig', {'comments': video.comments}) }}

            <div class="b-commentForm">
                <form method="post" action="{{ url('commentCreate', {'extId': video.extId }) }}">
                    <textarea name="text"></textarea>
                    <input type="submit">
                </form>
            </div>

        {% endif %}

    </div>

{% endblock %}